### ISSUE TITLE
SSLR PL/SQL toolkit unable to analyze scripts containing DB Links

### ISSUE THREAD

**Issue by sagarsanwal** [felipebz/zpa#123]
Hi,

I am trying to analyze a script using SSLR PL/SQL toolkit  containing DB Links in the format: 'DBLinkName.domainname.com', which is valid under SQL naming standards as well as matches with our organizational standards. The analyzer is unable to analyze the code and throws the below error:

com.sonar.sslr.api.RecognitionException: Parse error at line 15 column 78:

   12: sys.dual;
   13:  SELECT cars_batch.FUNC(V_VAR1) INTO V_num FROM sys.dual;
   14: 
  -->   SELECT LAST_NAME INTO V_NAME FROM SCHEMA_NAME.table_name@db_link_name.company.com WHERE DEPT_NUM = 10;
   16: 
   17:  Insert into pfe_cars_batch.table1 values(val1,val2,val3);
   18:  Insert into pfe_cars_batch.table1 values(val1,

	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:73)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:78)
	at org.sonar.sslr.internal.toolkit.SourceCodeModel.setSourceCode(SourceCodeModel.java:62)
	at org.sonar.sslr.internal.toolkit.ToolkitPresenter.onSourceCodeParseButtonClick(ToolkitPresenter.java:122)
	at org.sonar.sslr.internal.toolkit.ToolkitViewImpl$5.actionPerformed(ToolkitViewImpl.java:201)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

I have attached the scripts used for this.

[DB_LINK_EXAMPLE.txt](https://github.com/felipebz/zpa/files/3326022/DB_LINK_EXAMPLE.txt)

**Comment by sagarsanwal** [comment]
Additionally, if the naming format is changed from DBLinkName.domainname.com to DBLinkName.domainname or DBLinkName.com, the script gets analyzed properly.

**Comment by felipebz** [comment]
Nice find, @sagarsanwal. :+1:

Thanks!

**Comment by sagarsanwal** [comment]
Your welcome @felipebz 
I went through the suggested changes and they have been suggested for the current version 2.3.0.
Currently, I am working on building custom rules using version 2.2.0.

Can the suggested solution be extended to the 2.2.0 code by making similar changes to the DMLGrammar class?

**Comment by felipebz** [comment]
Yes, it can. :-) And this is the line: https://github.com/felipebz/zpa/blob/c4f5bd517a22cba923cc4468adc662ca7997e811/plsql-frontend/src/main/java/org/sonar/plugins/plsqlopen/api/DmlGrammar.java#L186

**Comment by sagarsanwal** [comment]
That worked like a charm :)
Thanks for the support @felipebz
