### ISSUE TITLE
ClassNotFoundException: org.jaxen.saxpath.base.XPathReader

### ISSUE THREAD

**Issue by phermsdorf** [felipebz/zpa#154]
Hi,

we just updated from a 2.x release of the SonarQube Plugin to the latest release 3.1.0 and encounter the following error messages during analysis:

``
rg.sonar.plsqlopen.squid.AnalysisException: Error executing checks on file PCK_ERLOESKONTO.PKB: Unable to initialize the XPath engine, perhaps because of an invalid query: //CREATE_PACKAGE_BODY[UNIT_NAME[starts-with(@tokenValue, 'PI_') or @tokenValue='PCK_OFL']]/DECLARE_SECTION//*[name() = 'SELECT_EXPRESSION' or name() = 'UPDATE_EXPRESSION' or name() = 'INSERT_EXPRESSION' or name() = 'DELETE_EXPRESSION']
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.walk(PlSqlAstWalker.kt:59)
	at org.sonar.plsqlopen.squid.AstScanner.scanFile(AstScanner.kt:86)
	at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanMainFile(PlSqlAstScanner.kt:75)
	at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.kt:67)
	at org.sonar.plsqlopen.PlSqlSquidSensor.execute$lambda-1(PlSqlSquidSensor.kt:78)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.sonar.plsqlopen.squid.AnalysisException: Unable to initialize the XPath engine, perhaps because of an invalid query: //CREATE_PACKAGE_BODY[UNIT_NAME[starts-with(@tokenValue, 'PI_') or @tokenValue='PCK_OFL']]/DECLARE_SECTION//*[name() = 'SELECT_EXPRESSION' or name() = 'UPDATE_EXPRESSION' or name() = 'INSERT_EXPRESSION' or name() = 'DELETE_EXPRESSION']
	at org.sonar.plsqlopen.checks.XPathCheck.query(XPathCheck.kt:45)
	at org.sonar.plsqlopen.checks.XPathCheck.visitFile(XPathCheck.kt:54)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.walk(PlSqlAstWalker.kt:50)
	... 13 common frames omitted
Caused by: java.lang.RuntimeException: org.jaxen.JaxenException: org.jaxen.saxpath.base.XPathReader
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.kt:33)
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.kt)
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery$Companion.create(AstNodeXPathQuery.kt:98)
	at org.sonar.plsqlopen.checks.XPathCheck.query(XPathCheck.kt:43)
	... 15 common frames omitted
Caused by: org.jaxen.JaxenException: org.jaxen.saxpath.base.XPathReader
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:125)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:142)
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.kt:31)
	... 18 common frames omitted
Caused by: org.jaxen.saxpath.SAXPathException: org.jaxen.saxpath.base.XPathReader
	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:152)
	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:110)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:113)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jaxen.saxpath.base.XPathReader
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:137)
	... 22 common frames omitted
``
This seems to be the same issue as #87 

Thanks for looking at the issue.

Bye Peter

**Comment by felipebz** [comment]
And it's caused by the same packaging error.... :facepalm:

Thanks for reporting this, @phermsdorf! I fixed it in the [version 3.1.1](https://github.com/felipebz/zpa/releases/tag/3.1.1).

**Comment by phermsdorf** [comment]
Works again. Thanks for fixing this, @felipebz !
