### ISSUE TITLE
unable to analyze .trsl files

### ISSUE THREAD

**Issue by csrvsk** [felipebz/zpa#163]
Hi,

I used PLSQL to scan a folder which contains .trsl (sql) files. But ZPA PLSQL Quality profile is unable to scan the this file, but at the end it says EXECUTION SUCCESS.

But when we check it on SonarUI, analysis report is empty.

**Following are the errors found in Scanner logs**

10:50:50.883 INFO: Sensor Z PL/SQL Analyzer [plsqlopen]
10:50:50.946 INFO: 2 source files to be analyzed
10:50:50.947 INFO: Concurrent mode enabled
10:50:51.093 WARN: Invalid character encountered in file /home/oracle/TRSL/tm_french_fr.trsl at line 76 for encoding UTF-8. Please fix file content or configure the encoding to be used using property 'sonar.sourceEncoding'.
10:50:52.508 DEBUG: 'tm_french_fr.trsl' generated metadata with charset 'UTF-8'
10:50:52.518 DEBUG: 'tm_spanish_es.trsl' generated metadata with charset 'windows-1252'
10:51:00.947 INFO: 0/2 files analyzed, current file: tm_french_fr.trsl
10:51:10.947 INFO: 0/2 files analyzed, current file: tm_french_fr.trsl
10:51:20.948 INFO: 0/2 files analyzed, current file: tm_french_fr.trsl
10:51:32.452 INFO: 0/2 files analyzed, current file: tm_french_fr.trsl
10:52:08.494 INFO: 0/2 files analyzed, current file: tm_french_fr.trsl
10:52:08.504 ERROR: Error during analysis of file tm_french_fr.trsl
org.sonar.plsqlopen.squid.AnalysisException: Unable to analyze file: tm_french_fr.trsl
        at org.sonar.plsqlopen.squid.AstScanner.getPlSqlVisitorContext(AstScanner.kt:129)
        at org.sonar.plsqlopen.squid.AstScanner.scanFile(AstScanner.kt:57)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanMainFile(PlSqlAstScanner.kt:75)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.kt:67)
        at org.sonar.plsqlopen.PlSqlSquidSensor.execute$lambda-1(PlSqlSquidSensor.kt:78)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.felipebz.flr.internal.vm.Machine.createNode(Machine.kt:153)
        at com.felipebz.flr.internal.vm.Instruction$RetInstruction.execute(Instruction.kt:173)
        at com.felipebz.flr.internal.vm.Machine.execute(Machine.kt:74)
        at com.felipebz.flr.internal.vm.Machine.execute(Machine.kt:62)
        at com.felipebz.flr.internal.vm.Machine.access$execute(Machine.kt:34)
        at com.felipebz.flr.internal.vm.Machine$Companion.parse(Machine.kt:199)
        at com.felipebz.flr.impl.Parser.parse(Parser.kt:81)
        at com.felipebz.flr.impl.Parser.parse(Parser.kt:75)
        at org.sonar.plsqlopen.squid.AstScanner.getPlSqlVisitorContext(AstScanner.kt:120)
        at org.sonar.plsqlopen.squid.AstScanner.scanFile(AstScanner.kt:57)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanMainFile(PlSqlAstScanner.kt:75)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.kt:67)
        at org.sonar.plsqlopen.PlSqlSquidSensor.execute$lambda-1(PlSqlSquidSensor.kt:78)
        at org.sonar.plsqlopen.PlSqlSquidSensor$$Lambda$522/0x00000008008a0440.accept(Unknown Source)
        ... 10 common frames omitted

10:52:08.504 ERROR: Error during analysis of file tm_spanish_es.trsl
org.sonar.plsqlopen.squid.AnalysisException: Unable to analyze file: tm_spanish_es.trsl
        at org.sonar.plsqlopen.squid.AstScanner.getPlSqlVisitorContext(AstScanner.kt:129)
        at org.sonar.plsqlopen.squid.AstScanner.scanFile(AstScanner.kt:57)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanMainFile(PlSqlAstScanner.kt:75)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.kt:67)
        at org.sonar.plsqlopen.PlSqlSquidSensor.execute$lambda-1(PlSqlSquidSensor.kt:78)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at org.sonar.plsqlopen.PlSqlSquidSensor.execute(PlSqlSquidSensor.kt:76)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:81)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:392)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:388)
        at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:357)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.felipebz.flr.internal.vm.Machine.createLeafNode(Machine.kt:162)
        at com.felipebz.flr.internal.vm.lexerful.TokenTypeExpression.execute(TokenTypeExpression.kt:34)
        at com.felipebz.flr.internal.vm.Machine.execute(Machine.kt:74)
        at com.felipebz.flr.internal.vm.Machine.execute(Machine.kt:62)
        at com.felipebz.flr.internal.vm.Machine.access$execute(Machine.kt:34)
        at com.felipebz.flr.internal.vm.Machine$Companion.parse(Machine.kt:199)
        at com.felipebz.flr.impl.Parser.parse(Parser.kt:81)
        at com.felipebz.flr.impl.Parser.parse(Parser.kt:75)
        at org.sonar.plsqlopen.squid.AstScanner.getPlSqlVisitorContext(AstScanner.kt:120)
        at org.sonar.plsqlopen.squid.AstScanner.scanFile(AstScanner.kt:57)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanMainFile(PlSqlAstScanner.kt:75)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.kt:67)
        at org.sonar.plsqlopen.PlSqlSquidSensor.execute$lambda-1(PlSqlSquidSensor.kt:78)
        at org.sonar.plsqlopen.PlSqlSquidSensor$$Lambda$522/0x00000008008a0440.accept(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at org.sonar.plsqlopen.PlSqlSquidSensor.execute(PlSqlSquidSensor.kt:76)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor$$Lambda$521/0x000000080089cc40.run(Unknown Source)

PLease let me know how to get this fixed.

Thanks
vsk

**Comment by csrvsk** [comment]
Hi Filepe,

Please let me know if you have any fix for this issue.

Thanks in advance

**Comment by felipebz** [comment]
Hi,

I've never seen this file extension, are you sure that the file contains Oracle PL/SQL code? Does it execute correctly on a Oracle database?

You could try to increase the memory using the SONAR_SCANNER_OPTS as described on the "Troubleshooting" section of the [SonarScanner docs](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/#header-9)
