### ISSUE TITLE
error "evaluate XPath" in the ZPA Toolkit

### ISSUE THREAD

**Issue by Zempik** [felipebz/zpa#164]
Good afternoon, my actions:
I run zpa toolkit in Windows 10 PowerShell 
```
java -jar zpa-toolkit-3.1.1.jar
```
```
java --version
openjdk 18 2022-03-22
OpenJDK Runtime Environment (build 18+36-2087)
```
OpenJDK 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
I enter simple PL/SQL code in Source Code
`grant select on OBJECT_RL to SVC;`
or
`SELECT * FROM DUAL;`
Parse Source Code
XPath query: `//IDENTIFIER` or `//GRANT` or something
Console:
```
java.lang.RuntimeException: org.jaxen.JaxenException: org.jaxen.saxpath.base.XPathReader
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.kt:33)
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.kt)
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery$Companion.create(AstNodeXPathQuery.kt:98)
	at com.felipebz.flr.internal.toolkit.ToolkitPresenter.onXPathEvaluateButtonClick(ToolkitPresenter.kt:115)
	at com.felipebz.flr.internal.toolkit.ToolkitViewImpl.initComponents$lambda-4(ToolkitViewImpl.kt:137)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6616)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6381)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4991)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jaxen.JaxenException: org.jaxen.saxpath.base.XPathReader
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:125)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:142)
	at com.felipebz.flr.xpath.api.AstNodeXPathQuery.<init>(AstNodeXPathQuery.kt:31)
	... 39 more
Caused by: org.jaxen.saxpath.SAXPathException: org.jaxen.saxpath.base.XPathReader
	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:152)
	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:110)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:113)
	... 41 more
Caused by: java.lang.ClassNotFoundException: org.jaxen.saxpath.base.XPathReader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.jaxen.saxpath.helpers.XPathReaderFactory.createReader(XPathReaderFactory.java:137)
	... 43 more
```

P.S. sslr-plsql-toolkit-3.8.0.4948.jar works correctly

**Comment by felipebz** [comment]
Hi,

Thanks for reporting this issue. I published a fixed version here: https://github.com/felipebz/zpa/releases/download/3.1.1/zpa-toolkit-3.1.1.1.jar
